const types = {
  AUTH_TOKEN: "AUTH_TOKEN",
  VALIDATE_INVITATION_CODE: "VALIDATE_INVITATION_CODE",
  HEADER_STYLES: "HEADER_STYLES",
  CURRENT_USER: "CURRENT_USER",
  SET_THREAD: "SET_THREAD",
  SET_SPINNER: "SET_SPINNER",
}

export default types;